export default {
	EDIT_SETTINGS_REQUEST: 'EDIT_SETTINGS_REQUEST',
	EDIT_SETTINGS_SUCCESS: 'EDIT_SETTINGS_SUCCESS',
	EDIT_SETTINGS_FAILURE: 'EDIT_SETTINGS_FAILURE',
	INITIALIZE_APP_REQUEST: 'INITIALIZE_APP_REQUEST',
	INITIALIZE_APP_SUCCESS: 'INITIALIZE_APP_SUCCESS',
	INITIALIZE_APP_FAILURE: 'INITIALIZE_APP_FAILURE',
	READ_APP_REQUEST: 'READ_APP_REQUEST',
	READ_APP_SUCCESS: 'READ_APP_SUCCESS',
	READ_APP_FAILURE: 'READ_APP_FAILURE',

	//USER
	ADD_USER_REQUEST: 'ADD_USER_REQUEST',
	ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
	ADD_USER_FAILURE: 'ADD_USER_FAILURE',
	READ_USER_REQUEST: 'READ_USER_REQUEST',
	READ_USER_SUCCESS: 'READ_USER_SUCCESS',
	READ_USER_FAILURE: 'READ_USER_FAILURE',

	//CUSTOM GAME SETTINGS
	BROWSE_DECKS_REQUEST: 'BROWSE_DECKS_REQUEST',
	BROWSE_DECKS_SUCCESS: 'BROWSE_DECKS_SUCCESS',
	BROWSE_DECKS_FAIURE: 'BROWSE_DECKS_FAIURE',

	//NON-API
	TOGGLE_LOADING_OVERLAY: 'TOGGLE_LOADING_OVERLAY',
	SET_DEVICE_DETAILS: 'SET_DEVICE_DETAILS',
	SET_APP: 'SET_APP',
	MODAL_TOGGLE_SIGNOUT: 'MODAL_TOGGLE_SIGNOUT',
	MODAL_TOGGLE_RESET_GAME: 'MODAL_TOGGLE_RESET_GAME',
	MODAL_TOGGLE_RESTART_GAME: 'MODAL_TOGGLE_RESTART_GAME',
	MODAL_TOGGLE_RESET_TEAM: 'MODAL_TOGGLE_RESET_TEAM',
	MODAL_TOGGLE_AS_LEADER: 'MODAL_TOGGLE_AS_LEADER',
}