export default {
	EDIT_SETTINGS_REQUEST: 'EDIT_SETTINGS_REQUEST',
	EDIT_SETTINGS_SUCCESS: 'EDIT_SETTINGS_SUCCESS',
	EDIT_SETTINGS_FAILURE: 'EDIT_SETTINGS_FAILURE',
	INITIALIZE_APP_REQUEST: 'INITIALIZE_APP_REQUEST',
	INITIALIZE_APP_SUCCESS: 'INITIALIZE_APP_SUCCESS',
	INITIALIZE_APP_FAIURE: 'INITIALIZE_APP_FAIURE',

	//CUSTOM GAME SETTINGS
	BROWSE_DECKS_REQUEST: 'BROWSE_DECKS_REQUEST',
	BROWSE_DECKS_SUCCESS: 'BROWSE_DECKS_SUCCESS',
	BROWSE_DECKS_FAIURE: 'BROWSE_DECKS_FAIURE',
}