export default {
	ADD_CARD_REQUEST: 'ADD_CARD_REQUEST',
	ADD_CARD_SUCCESS: 'ADD_CARD_SUCCESS',
	ADD_CARD_FAILURE: 'ADD_CARD_FAILURE',
	EDIT_CARD_REQUEST: 'EDIT_CARD_REQUEST',
	EDIT_CARD_SUCCESS: 'EDIT_CARD_SUCCESS',
	EDIT_CARD_FAILURE: 'EDIT_CARD_FAILURE',
	BROWSE_CARD_REQUEST: 'BROWSE_CARD_REQUEST',
	BROWSE_CARD_SUCCESS: 'BROWSE_CARD_SUCCESS',
	BROWSE_CARD_FAILURE: 'BROWSE_CARD_FAILURE',
	READ_CARD_REQUEST: 'READ_CARD_REQUEST',
	READ_CARD_SUCCESS: 'READ_CARD_SUCCESS',
	READ_CARD_FAILURE: 'READ_CARD_FAILURE',
	DELETE_CARD_REQUEST: 'DELETE_CARD_REQUEST',
	DELETE_CARD_SUCCESS: 'DELETE_CARD_SUCCESS',
	DELETE_CARD_FAILURE: 'DELETE_CARD_FAILURE',

	//GRID CARDS
	GET_PLAYING_CARDS_REQUEST: 'GET_PLAYING_CARDS_REQUEST',
	GET_PLAYING_CARDS_SUCCESS: 'GET_PLAYING_CARDS_SUCCESS',
	GET_PLAYING_CARDS_FAILURE: 'GET_PLAYING_CARDS_FAILURE',
	GET_GRID_CARDS_REQUEST: 'GET_GRID_CARDS_REQUEST',
	GET_GRID_CARDS_SUCCESS: 'GET_GRID_CARDS_SUCCESS',
	GET_GRID_CARDS_FAILURE: 'GET_GRID_CARDS_FAILURE',

	//VOTES
	SUBMIT_VOTES_REQUEST: 'SUBMIT_VOTES_REQUEST',
	SUBMIT_VOTES_SUCCESS: 'SUBMIT_VOTES_SUCCESS',
	SUBMIT_VOTES_FAILURE: 'SUBMIT_VOTES_FAILURE',

	//DECK
	ADD_DECK_REQUEST: 'ADD_DECK_REQUEST',
	ADD_DECK_SUCCESS: 'ADD_DECK_SUCCESS',
	ADD_DECK_FAILURE: 'ADD_DECK_FAILURE',
	EDIT_DECK_REQUEST: 'EDIT_DECK_REQUEST',
	EDIT_DECK_SUCCESS: 'EDIT_DECK_SUCCESS',
	EDIT_DECK_FAILURE: 'EDIT_DECK_FAILURE',
	BROWSE_DECK_REQUEST: 'BROWSE_DECK_REQUEST',
	BROWSE_DECK_SUCCESS: 'BROWSE_DECK_SUCCESS',
	BROWSE_DECK_FAILURE: 'BROWSE_DECK_FAILURE',
	READ_DECK_REQUEST: 'READ_DECK_REQUEST',
	READ_DECK_SUCCESS: 'READ_DECK_SUCCESS',
	READ_DECK_FAILURE: 'READ_DECK_FAILURE',
	DELETE_DECK_REQUEST: 'DELETE_DECK_REQUEST',
	DELETE_DECK_SUCCESS: 'DELETE_DECK_SUCCESS',
	DELETE_DECK_FAILURE: 'DELETE_DECK_FAILURE',

	//NON-API
	SET_PLAYING_DECKS: 'SET_PLAYING_DECKS',
}