export default {
	END_GAME_REQUEST: 'END_GAME_REQUEST',
	END_GAME_SUCCESS: 'END_GAME_SUCCESS',
	END_GAME_FAILURE: 'END_GAME_FAILURE',
	RESET_GAME_REQUEST: 'RESET_GAME_REQUEST',
	RESET_GAME_SUCCESS: 'RESET_GAME_SUCCESS',
	RESET_GAME_FAILURE: 'RESET_GAME_FAILURE',
	RESTART_GAME_REQUEST: 'RESTART_GAME_REQUEST',
	RESTART_GAME_SUCCESS: 'RESTART_GAME_SUCCESS',
	RESTART_GAME_FAILURE: 'RESTART_GAME_FAILURE',
	PAUSE_GAME_REQUEST: 'PAUSE_GAME_REQUEST',
	PAUSE_GAME_SUCCESS: 'PAUSE_GAME_SUCCESS',
	PAUSE_GAME_FAILURE: 'PAUSE_GAME_FAILURE',
	RESUME_GAME_REQUEST: 'RESUME_GAME_REQUEST',
	RESUME_GAME_SUCCESS: 'RESUME_GAME_SUCCESS',
	RESUME_GAME_FAILURE: 'RESUME_GAME_FAILURE',
	READ_GAME_REQUEST: 'READ_GAME_REQUEST',
	READ_GAME_SUCCESS: 'READ_GAME_SUCCESS',
	READ_GAME_FAILURE: 'READ_GAME_FAILURE',
	SET_GAME: 'SET_GAME',

	//ROUNDS
	ADD_ROUND_REQUEST: 'ADD_ROUND_REQUEST',
	ADD_ROUND_SUCCESS: 'ADD_ROUND_SUCCESS',
	ADD_ROUND_FAILURE: 'ADD_ROUND_FAILURE',
	EDIT_ROUND_REQUEST: 'EDIT_ROUND_REQUEST',
	EDIT_ROUND_SUCCESS: 'EDIT_ROUND_SUCCESS',
	EDIT_ROUND_FAILURE: 'EDIT_ROUND_FAILURE',

	//MOD
	ADD_MOD_REQUEST: 'ADD_MOD_REQUEST',
	ADD_MOD_SUCCESS: 'ADD_MOD_SUCCESS',
	ADD_MOD_FAILURE: 'ADD_MOD_FAILURE',
	DELETE_MOD_REQUEST: 'DELETE_MOD_REQUEST',
	DELETE_MOD_SUCCESS: 'DELETE_MOD_SUCCESS',
	DELETE_MOD_FAILURE: 'DELETE_MOD_FAILURE',

	//CONCLUSION
	EDIT_CONCLUSION_REQUEST: 'EDIT_CONCLUSION_REQUEST',
	EDIT_CONCLUSION_SUCCESS: 'EDIT_CONCLUSION_SUCCESS',
	EDIT_CONCLUSION_FAILURE: 'EDIT_CONCLUSION_FAILURE',

	//NON-API
	SHIFT_TURN: 'SHIFT_TURN'
}